environment:
  COVERALLS_REPO_TOKEN:
    secure: 2NJ5Ct55cHJ9WEg3xbSqCuv0rdgzzb6pnzOIG5OkMbTndw3wOBrXntWFoQrXiMFi
    # this is pytest's token in coveralls.io, encrypted
    # using pytestbot account as detailed here:
    # https://www.appveyor.com/docs/build-configuration#secure-variables

  matrix:
  # note: please use "tox --listenvs" to populate the build matrix below
  - TOXENV: "linting"
  - TOXENV: "py26"
  - TOXENV: "py27"
  - TOXENV: "py33"
  - TOXENV: "py34"
  - TOXENV: "py35"
  - TOXENV: "pypy"
  - TOXENV: "py27-pexpect"
  - TOXENV: "py27-xdist"
  - TOXENV: "py27-trial"
  - TOXENV: "py35-pexpect"
  - TOXENV: "py35-xdist"
  - TOXENV: "py35-trial"
  - TOXENV: "py27-nobyte"
  - TOXENV: "doctesting"
  - TOXENV: "freeze"
  - TOXENV: "docs"

install:
  - echo Installed Pythons
  - dir c:\Python*

  - if "%TOXENV%" == "pypy" scripts\install-pypy.bat

  - C:\Python35\python -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python35\python -m tox
  # coveralls is not in tox's envlist, plus for PRs the secure variable
  # is not defined so we have to check for it
  - if defined COVERALLS_REPO_TOKEN C:\Python35\python -m tox -e coveralls
